twilio:
  account_sid: ""
  auth_token: ""
  phone_number: "+14155238886"

llm:
  provider: "gemini"
  api_key: ""
  model: "gemini-2.0-flash"
  max_tokens: 1024
  temperature: 0.7

mongodb:
  connection_string: ""
  database: ""

processing:
  max_concurrent_books: 5
  response_timeout: 30
  aggregation_timeout: 30